version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "9230:9230" # chrome debugger
    links:
      - mysql
    volumes:
      - ./:/container:ro
  mysql:
    image: mysql:5.7
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
