version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "9229:9229" # chrome debugger
    links:
      - mysql
    volumes:
      - ./app:/container/app:ro
      - ./db:/container/db:ro
      - ./knexfile.js:/container/knexfile.js:ro
      - ./package.json:/container/package.json:ro
      - ./package-lock.json:/container/package-lock.json:ro
      - ./test:/container/test:ro
  mysql:
    image: mysql:5.7
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
